import 'dart:io';
import 'dart:math';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:package_info_plus/package_info_plus.dart';

import '../utils/logger.dart';

/// Keystore-backed storage plus the device fingerprint built on top of it.
///
/// The fingerprint is a *hint* to the server, never proof — a rooted device
/// can forge any of it. Real protection is App Check + Play Integrity; this
/// exists so `recordDevice` can spot the same handset farming many accounts,
/// and so obvious emulators can be scored down.
class SecureStorageService {
  SecureStorageService({FlutterSecureStorage? storage})
    : _storage =
          storage ??
          const FlutterSecureStorage(
            aOptions: AndroidOptions(encryptedSharedPreferences: true),
          );

  final FlutterSecureStorage _storage;

  static const _deviceIdKey = 'robux_device_id';

  Map<String, dynamic>? _cached;

  /// A stable per-install id.
  ///
  /// Deliberately generated by us and kept in the keystore-backed store rather
  /// than using a hardware identifier: Play policy forbids persistent hardware
  /// ids for this purpose, and an app reinstall *should* look like a new
  /// device. It survives app updates, which is what the device cap needs.
  Future<String> deviceId() async {
    final existing = await _read(_deviceIdKey);
    if (existing != null && existing.length >= 16) return existing;

    final fresh = _randomId();
    try {
      await _storage.write(key: _deviceIdKey, value: fresh);
    } catch (e) {
      // A device with a broken keystore still has to be able to earn; it just
      // gets a new id each launch and is treated as a new device.
      log.w('secure storage write failed', e);
    }
    return fresh;
  }

  Future<String?> _read(String key) async {
    try {
      return await _storage.read(key: key);
    } catch (e) {
      log.w('secure storage read failed', e);
      return null;
    }
  }

  /// The payload for `DeviceContext` on the server. Cached for the process
  /// lifetime — nothing in it changes without an app restart.
  Future<Map<String, dynamic>> context() async {
    if (_cached != null) return _cached!;

    final id = await deviceId();
    final pkg = await _packageInfo();

    var platform = 'unknown';
    var osVersion = '';
    var model = '';
    var physical = true;

    try {
      final info = DeviceInfoPlugin();
      if (!kIsWeb && Platform.isAndroid) {
        final a = await info.androidInfo;
        platform = 'android';
        osVersion = 'Android ${a.version.release} (SDK ${a.version.sdkInt})';
        model = '${a.manufacturer} ${a.model}';
        physical = a.isPhysicalDevice;
      } else if (!kIsWeb && Platform.isIOS) {
        final i = await info.iosInfo;
        platform = 'ios';
        osVersion = '${i.systemName} ${i.systemVersion}';
        model = i.utsname.machine;
        physical = i.isPhysicalDevice;
      } else if (kIsWeb) {
        platform = 'web';
      }
    } catch (e) {
      log.w('device info unavailable', e);
    }

    return _cached = {
      'deviceId': id,
      'platform': platform,
      'osVersion': osVersion,
      'model': model,
      'appVersion': pkg,
      'isPhysicalDevice': physical,
      'isDebug': kDebugMode,
      'integrityScore': _score(physical: physical, model: model),
    };
  }

  Future<String> _packageInfo() async {
    try {
      final p = await PackageInfo.fromPlatform();
      return '${p.version}+${p.buildNumber}';
    } catch (_) {
      return 'unknown';
    }
  }

  /// A crude 0–100 confidence that this is a real handset.
  ///
  /// Only ever *lowers* confidence on strong signals, because a false positive
  /// here blocks a paying user from earning. The server decides what to do
  /// with a low score; it does not hard-block on it.
  int _score({required bool physical, required String model}) {
    var score = 100;
    if (!physical) score -= 60;
    if (kDebugMode) score -= 20;

    final m = model.toLowerCase();
    const emulatorHints = ['sdk_gphone', 'emulator', 'genymotion', 'generic'];
    if (emulatorHints.any(m.contains)) score -= 40;

    return score.clamp(0, 100);
  }

  /// 32 hex chars from the platform's CSPRNG.
  static String _randomId() {
    final r = Random.secure();
    return List.generate(
      16,
      (_) => r.nextInt(256),
    ).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }
}
