// File generated by FlutterFire CLI.
// Values mirror android/app/google-services.json and
// ios/Runner/GoogleService-Info.plist for the `robux-box1` project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOuRGpgYkQ3-N7eKPfu_zsgi3n2zuVyGI',
    appId: '1:878768707356:android:9fad7a36fb0c6a30d5ccd9',
    messagingSenderId: '878768707356',
    projectId: 'robux-box1',
    storageBucket: 'robux-box1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdax2fx-VVbs83eVpfpgo89gbcHQJrzT4',
    appId: '1:878768707356:ios:52c7697ce662ac93d5ccd9',
    messagingSenderId: '878768707356',
    projectId: 'robux-box1',
    storageBucket: 'robux-box1.firebasestorage.app',
    iosBundleId: 'com.robuxbox.app',
  );

  // Web is only used for the `flutter build web` UI-preview build; it shares
  // the Android API key, which is domain/package restricted server-side.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuRGpgYkQ3-N7eKPfu_zsgi3n2zuVyGI',
    appId: '1:878768707356:android:9fad7a36fb0c6a30d5ccd9',
    messagingSenderId: '878768707356',
    projectId: 'robux-box1',
    storageBucket: 'robux-box1.firebasestorage.app',
  );
}
